# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45fa141225715dbf8e74f0670437d462ca220233f14489554777d55a2284e7d886da35f6ce3593b55128785fcfeb1d18cdf8b995ac04e1536d0d7c0a0611f87f
  facebook_app_id: 897497560295968
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 1191d47a2dcd378548602b4c4fd007e4b2bc2c33988d3c70207187c37cbf0c9e0d35ed1afa4287009a0e73f1a4b2dff7bb7059d3c0694cacb5dd05f8afbec43c
  facebook_app_id: 897497560295968
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 897497560295968
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
